system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
zap:
  level: 'info'
  format: 'console'
  prefix: '[github.com/the7s/gin-vue-blog/server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

#LowercaseColorLevelEncoder